export const kenneyBackgroundBase = "/assets/vendor/kenney/background-elements";
export const openGameArtEffectBase = "/assets/vendor/opengameart/effects";

export const backgroundAssets = {
  sky: `${kenneyBackgroundBase}/sky.png`,
  cloud1: `${kenneyBackgroundBase}/cloud1.png`,
  cloud2: `${kenneyBackgroundBase}/cloud2.png`,
  clouds1: `${kenneyBackgroundBase}/clouds1.png`,
  hills1: `${kenneyBackgroundBase}/hills1.png`,
  hills2: `${kenneyBackgroundBase}/hills2.png`,
  mountain1: `${kenneyBackgroundBase}/mountain1.png`,
  mountain2: `${kenneyBackgroundBase}/mountain2.png`,
  pointyMountains: `${kenneyBackgroundBase}/pointy_mountains.png`,
  temple: `${kenneyBackgroundBase}/temple.png`,
  houseFront: `${kenneyBackgroundBase}/house_front_short.png`,
  houseSide: `${kenneyBackgroundBase}/house_side_short.png`,
  fence: `${kenneyBackgroundBase}/fence.png`,
  grass1: `${kenneyBackgroundBase}/grass1.png`,
  grass2: `${kenneyBackgroundBase}/grass2.png`,
  tree01: `${kenneyBackgroundBase}/tree01.png`,
  tree04: `${kenneyBackgroundBase}/tree04.png`,
  tree08: `${kenneyBackgroundBase}/tree08.png`,
  tree13: `${kenneyBackgroundBase}/tree13.png`
} as const;

export type BackgroundAssetKey = keyof typeof backgroundAssets;

export const effectAssets = {
  spark: `${openGameArtEffectBase}/spark_sprite_strip9.png`,
  sparkAlt: `${openGameArtEffectBase}/spark_sprite2_strip9.png`,
  toonExplosion: `${openGameArtEffectBase}/toon_explosion_31.png`
} as const;

export type EffectAssetKey = keyof typeof effectAssets;

export const characterAssets = {
  davidActions: "/assets/characters/david/david-actions.png",
  davidRuntimeActions: "/assets/characters/david/david-actions-runtime.png",
  davidIcon: "/assets/characters/david/david-icon.png",
  davidMissing: "/assets/characters/david/david-missing.png",
  davidParts: "/assets/characters/david/david-parts.png",
  eagleActions: "/assets/characters/eagle/eagle-actions.png",
  eagleRuntimeActions: "/assets/characters/eagle/eagle-actions-runtime.png",
  eagleIcon: "/assets/characters/eagle/eagle-icon.png",
  eagleMissing: "/assets/characters/eagle/eagle-missing.png",
  eagleParts: "/assets/characters/eagle/eagle-parts.png",
  goliathActions: "/assets/characters/goliath/goliath-actions.png",
  goliathRuntimeActions: "/assets/characters/goliath/goliath-actions-runtime.png",
  goliathIcon: "/assets/characters/goliath/goliath-icon.png",
  goliathMissing: "/assets/characters/goliath/goliath-missing.png",
  goliathParts: "/assets/characters/goliath/goliath-parts.png",
  hippoActions: "/assets/characters/hippo/hippo-actions.png",
  hippoRuntimeActions: "/assets/characters/hippo/hippo-actions-runtime.png",
  hippoIcon: "/assets/characters/hippo/hippo-icon.png",
  hippoMissing: "/assets/characters/hippo/hippo-missing.png",
  hippoParts: "/assets/characters/hippo/hippo-parts.png",
  honeyBadgerActions: "/assets/characters/honey-badger/honey-badger-actions.png",
  honeyBadgerRuntimeActions: "/assets/characters/honey-badger/honey-badger-actions-runtime.png",
  honeyBadgerIcon: "/assets/characters/honey-badger/honey-badger-icon.png",
  lionActions: "/assets/characters/lion/lion-actions.png",
  lionRuntimeActions: "/assets/characters/lion/lion-actions-runtime.png",
  lionIcon: "/assets/characters/lion/lion-icon.png",
  chefBoyardeeActions: "/assets/characters/chef-boyardee/chef-boyardee-actions.png",
  chefBoyardeeRuntimeActions: "/assets/characters/chef-boyardee/chef-boyardee-actions-runtime.png",
  chefBoyardeeIcon: "/assets/characters/chef-boyardee/chef-boyardee-icon.png",
  marthaStewartActions: "/assets/characters/martha-stewart/martha-stewart-actions.png",
  marthaStewartRuntimeActions: "/assets/characters/martha-stewart/martha-stewart-actions-runtime.png",
  marthaStewartIcon: "/assets/characters/martha-stewart/martha-stewart-icon.png",
  stephenHawkingActions: "/assets/characters/stephen-hawking/stephen-hawking-actions.png",
  stephenHawkingRuntimeActions: "/assets/characters/stephen-hawking/stephen-hawking-actions-runtime.png",
  stephenHawkingIcon: "/assets/characters/stephen-hawking/stephen-hawking-icon.png",
  helenKellerActions: "/assets/characters/helen-keller/helen-keller-actions.png",
  helenKellerRuntimeActions: "/assets/characters/helen-keller/helen-keller-actions-runtime.png",
  helenKellerIcon: "/assets/characters/helen-keller/helen-keller-icon.png",
  turtleActions: "/assets/characters/turtle/turtle-actions.png",
  turtleRuntimeActions: "/assets/characters/turtle/turtle-actions-runtime.png",
  turtleIcon: "/assets/characters/turtle/turtle-icon.png",
  abrahamLincolnActions: "/assets/characters/abraham-lincoln/abraham-lincoln-actions.png",
  abrahamLincolnRuntimeActions: "/assets/characters/abraham-lincoln/abraham-lincoln-actions-runtime.png",
  abrahamLincolnIcon: "/assets/characters/abraham-lincoln/abraham-lincoln-icon.png",
  koolAidManActions: "/assets/characters/kool-aid-man/kool-aid-man-actions.png",
  koolAidManRuntimeActions: "/assets/characters/kool-aid-man/kool-aid-man-actions-runtime.png",
  koolAidManIcon: "/assets/characters/kool-aid-man/kool-aid-man-icon.png",
  slimerActions: "/assets/characters/slimer/slimer-actions.png",
  slimerRuntimeActions: "/assets/characters/slimer/slimer-actions-runtime.png",
  slimerIcon: "/assets/characters/slimer/slimer-icon.png",
  stayPuftActions: "/assets/characters/stay-puft/stay-puft-actions.png",
  stayPuftRuntimeActions: "/assets/characters/stay-puft/stay-puft-actions-runtime.png",
  stayPuftIcon: "/assets/characters/stay-puft/stay-puft-icon.png",
  dorothyActions: "/assets/characters/dorothy/dorothy-actions.png",
  dorothyRuntimeActions: "/assets/characters/dorothy/dorothy-actions-runtime.png",
  dorothyIcon: "/assets/characters/dorothy/dorothy-icon.png",
  sophiaActions: "/assets/characters/sophia/sophia-actions.png",
  sophiaRuntimeActions: "/assets/characters/sophia/sophia-actions-runtime.png",
  sophiaIcon: "/assets/characters/sophia/sophia-icon.png",
  blancheActions: "/assets/characters/blanche/blanche-actions.png",
  blancheRuntimeActions: "/assets/characters/blanche/blanche-actions-runtime.png",
  blancheIcon: "/assets/characters/blanche/blanche-icon.png",
  roseActions: "/assets/characters/rose/rose-actions.png",
  roseRuntimeActions: "/assets/characters/rose/rose-actions-runtime.png",
  roseIcon: "/assets/characters/rose/rose-icon.png",
  trexActions: "/assets/characters/trex/trex-actions.png",
  trexRuntimeActions: "/assets/characters/trex/trex-actions-runtime.png",
  trexIcon: "/assets/characters/trex/trex-icon.png",
  trexMissing: "/assets/characters/trex/trex-missing.png",
  trexParts: "/assets/characters/trex/trex-parts.png"
} as const;

export type CharacterAssetKey = keyof typeof characterAssets;
